// SHELL SHOCK: LIVE ACTION service worker (engine v2). Generated by ss_engine/build_assets.py - do not edit by hand.
// Core shell + engine art are precached on install; every other same-origin GET (level scripts, level art) is cached on first
// use, so a scene played once loads instantly and works offline. Each deploy gets a new VERSION (content hash) -> new cache;
// old caches are deleted on activate. index.html / assets.json are network-first (fresh deploys win), everything else cache-first.
const VERSION = "c66d54036771";
const CACHE = "ssla-" + VERSION;
const PRECACHE = ["./", "index.html", "assets.json", "manifest.webmanifest", "atlas_amber.png", "atlas_donny.png", "atlas_gunner.png", "atlas_lenny.png", "atlas_miko.png", "atlas_ninja.png", "atlas_rafe.png", "atlas_ramrod.png", "atlas_razor.png", "atlas_scorcher.png", "atlas_zap.png", "ball.png", "drill.png", "hallway.jpg", "hud_portraits.png", "icon180.png", "icon192.png", "icon512.png", "l1_lobby.jpg", "l1_twist.png", "levels/enemies_street.png", "map_bg.jpg", "room.jpg", "shared_sprites.png", "sp_donny.png", "sp_lenny.png", "sp_miko.png", "sp_rafe.png", "stairs.png", "stick.png", "title_bg.jpg", "title_logo.png"];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: "reload" })).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith("ssla-") && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
const FRESH = (u) => u.pathname.endsWith("/") || /\/(index\.html|assets\.json|sw\.js)$/.test(u.pathname) || /[?&](t|r)=\d/.test(u.search);
self.addEventListener("fetch", (e) => {
  const req = e.request, u = new URL(req.url);
  if (req.method !== "GET" || u.origin !== location.origin || u.pathname.indexOf("/rec/") >= 0) return;
  if (req.mode === "navigate" || FRESH(u)) {
    e.respondWith(fetch(req).then((r) => { if (r.ok) { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req.mode === "navigate" ? new URL("index.html", self.registration.scope).href : req, cp)); } return r; })
      .catch(() => caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true }).then((m) => m || c.match(new URL("index.html", self.registration.scope).href)))));
    return;
  }
  e.respondWith(caches.open(CACHE).then((c) => c.match(req).then((m) => m || fetch(req).then((r) => { if (r.ok) c.put(req, r.clone()); return r; })
    .catch(() => c.match(req, { ignoreSearch: true }).then((m2) => m2 || Response.error())))));
});
