// SHELL SHOCK: LIVE ACTION service worker (engine v2). Generated by ss_engine/build_assets.py - do not edit by hand.
// Core shell + engine art are precached on install; every other same-origin GET (level scripts, level art) is cached on first
// use, so a scene played once loads instantly and works offline. Each deploy gets a new VERSION (content hash) -> new cache;
// old caches are deleted on activate. index.html / assets.json are network-first (fresh deploys win), everything else cache-first.
const VERSION = "__VERSION__";
const CACHE = "ssla-" + VERSION;
const PRECACHE = __PRECACHE__;
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: "reload" })).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith("ssla-") && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
const FRESH = (u) => u.pathname.endsWith("/") || /\/(index\.html|assets\.json|sw\.js)$/.test(u.pathname) || /[?&](t|r)=\d/.test(u.search);
self.addEventListener("fetch", (e) => {
  const req = e.request, u = new URL(req.url);
  if (req.method !== "GET" || u.origin !== location.origin || u.pathname.indexOf("/rec/") >= 0) return;
  if (req.mode === "navigate" || FRESH(u)) {
    e.respondWith(fetch(req).then((r) => { if (r.ok) { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req.mode === "navigate" ? new URL("index.html", self.registration.scope).href : req, cp)); } return r; })
      .catch(() => caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true }).then((m) => m || c.match(new URL("index.html", self.registration.scope).href)))));
    return;
  }
  e.respondWith(caches.open(CACHE).then((c) => c.match(req).then((m) => m || fetch(req).then((r) => { if (r.ok) c.put(req, r.clone()); return r; })
    .catch(() => c.match(req, { ignoreSearch: true }).then((m2) => m2 || Response.error())))));
});
